version: "3.8"
services:
  traefik:
    image: traefik:v2.11.0
    container_name: transcribo-secure-traefik
    command:
      - "--api.dashboard=true"
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=transcribo-secure-network"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--providers.file.watch=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./infrastructure/docker/traefik/selfsigned:/etc/traefik/dynamic:ro"
      - "./infrastructure/docker/letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - transcribo-secure-network
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: transcribo-secure-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infrastructure/docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - transcribo-secure-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  minio:
    image: minio/minio
    container_name: transcribo-secure-minio
    command: server --console-address ":9001" /data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - "./infrastructure/docker/.minio/data:/data"
      - "./.env:/app/.env:ro"
    networks:
      - transcribo-secure-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.minio-api.rule=Host(`minio-api.localhost`)"
      - "traefik.http.routers.minio-console.rule=Host(`minio-console.localhost`)"
      - "traefik.http.routers.minio-api.entrypoints=websecure"
      - "traefik.http.routers.minio-console.entrypoints=websecure"
      - "traefik.http.routers.minio-api.tls=true"
      - "traefik.http.routers.minio-console.tls=true"
      - "traefik.http.routers.minio-api.service=minio"
      - "traefik.http.routers.minio-console.service=minio"
      - "traefik.http.services.minio.loadbalancer.server.port=9000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped

  backend:
    build:
      context: "./backend"
      dockerfile: Dockerfile
      args:
        BUILDKIT_PROGRESS: plain
    container_name: transcribo-secure-backend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - MINIO_HOST=${MINIO_HOST}
      - MINIO_PORT=${MINIO_PORT}
      - MINIO_ACCESS_KEY=${MINIO_ROOT_USER}
      - MINIO_SECRET_KEY=${MINIO_ROOT_PASSWORD}
      - AZURE_KEYVAULT_URL=${AZURE_KEYVAULT_URL}
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
      - HF_AUTH_TOKEN=${HF_AUTH_TOKEN}
      - MAX_UPLOAD_SIZE=${MAX_UPLOAD_SIZE}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - TRANSCRIBER_URL=http://transcriber:8000
    command: ["./wait-for-it.sh", "-t", "30", "postgres:5432", "--", "./wait-for-it.sh", "-t", "30", "minio:9000", "--", "python", "-m", "src.main"]
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
      otel-collector:
        condition: service_started
    networks:
      - transcribo-secure-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.localhost`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.services.backend.loadbalancer.server.port=8080"
    volumes:
      - "./.env:/app/.env:ro"
    restart: unless-stopped

  frontend:
    build:
      context: "./frontend"
      dockerfile: Dockerfile
      args:
        BUILDKIT_PROGRESS: plain
    container_name: transcribo-secure-frontend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"
    environment:
      - BACKEND_API_URL=http://backend:8080/api/v1
      - REFRESH_INTERVAL=${REFRESH_INTERVAL}
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
    volumes:
      - "./frontend:/app"
      - "./.env:/app/.env:ro"
    networks:
      - transcribo-secure-network
    depends_on:
      otel-collector:
        condition: service_started
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`app.localhost`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.services.frontend.loadbalancer.server.port=8501"
    restart: unless-stopped

  transcriber:
    build:
      context: "./transcriber"
      dockerfile: Dockerfile
      args:
        BUILDKIT_PROGRESS: plain
        HF_AUTH_TOKEN: ${HF_AUTH_TOKEN}
    container_name: transcribo-secure-transcriber
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"
    environment:
      - BACKEND_API_URL=http://backend:8080/api/v1
      - DEVICE=${DEVICE}
      - BATCH_SIZE=${BATCH_SIZE}
      - HF_AUTH_TOKEN=${HF_AUTH_TOKEN}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
    volumes:
      - "transcriber_data:/tmp/transcriber"
      - "huggingface_cache:/root/.cache/huggingface"
      - "pip_cache:/root/.cache/pip"
      - "torch_cache:/root/.cache/torch"
      - "./.env:/app/.env:ro"
    depends_on:
      otel-collector:
        condition: service_started
    networks:
      - transcribo-secure-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.transcriber.rule=Host(`transcriber.localhost`)"
      - "traefik.http.services.transcriber.loadbalancer.server.port=8000"
      - "traefik.http.routers.transcriber.entrypoints=websecure"
      - "traefik.http.routers.transcriber.tls=true"

  otel-collector:
    image: otel/opentelemetry-collector:0.96.0
    container_name: transcribo-secure-otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./config/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    depends_on:
      - loki
      - tempo
    networks:
      - transcribo-secure-network
    restart: unless-stopped

  loki:
    image: grafana/loki:2.9.0
    container_name: transcribo-secure-loki
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki_data:/loki
    networks:
      - transcribo-secure-network
    restart: unless-stopped

  tempo:
    image: grafana/tempo:2.3.0
    container_name: transcribo-secure-tempo
    command: ["--target=all", "--storage.trace.backend=local", "--storage.trace.local.path=/tmp/tempo"]
    volumes:
      - tempo_data:/tmp/tempo
    networks:
      - transcribo-secure-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.2.0
    container_name: transcribo-secure-grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_PROXY_ENABLED=true
      - GF_SERVER_ROOT_URL=https://metrics.localhost
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    volumes:
      - grafana_data:/var/lib/grafana
      - ./infrastructure/docker/grafana/provisioning:/etc/grafana/provisioning
      - ./infrastructure/docker/grafana/dashboards:/var/lib/grafana/dashboards
      - "./.env:/app/.env:ro"
    networks:
      - transcribo-secure-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`metrics.localhost`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
    restart: unless-stopped

networks:
  transcribo-secure-network:
    name: transcribo-secure-network

volumes:
  transcriber_data:
  postgres_data:
  huggingface_cache:
  pip_cache:
  torch_cache:
  grafana_data:
  loki_data:
  tempo_data:
