http:
  routers:
    minio-api:
      rule: "Host(`minio-api.localhost`)"
      entryPoints:
        - websecure
      service: minio-api
      tls: {}

    minio-console:
      rule: "Host(`minio-console.localhost`)"
      entryPoints:
        - websecure
      service: minio-console
      tls: {}

  services:
    minio-api:
      loadBalancer:
        servers:
          - url: "http://minio:9000"
        passHostHeader: true

    minio-console:
      loadBalancer:
        servers:
          - url: "http://minio:9001"
        passHostHeader: true
